Fix multiple marquees not being able to have different axis and reverse values
jagnani73/react-easy-marquee pull request #23
Opened 2022-01-27 06:29 UTC by elliott-w

Before:
All instances of Marquee used the same keyframes animation name for each slide offset:
`slide-1`
`slide0`
`slide1`
Thus every Marquee would have the same animation behaviour as the last Marquee initialised.

Now:
Every new Marquee instance gets an id - starts at 0 and increments by 1 for each new Marquee. Thus the keyframe animation names for Marquee 0 become:
`m0slide-1`
`m0slide0`
`m0slide1`
And keyframe animation names for Marquee 1 become:
`m1slide-1`
`m1slide0`
`m1slide1`
Allowing each Marquee to have it's own animation behaviour (axis and reverse).

Notes:
Probably should be using css modules rather than style tags, but this is the quickest fix.

2022-01-27 08:45 UTC, jagnani73 requested changes

2022-01-27 08:45 UTC, jagnani73 commented on src/index.tsx
> +  const [id, setId] = useState(0)
@elliott-w can you please pass the generic type for the useState

2022-01-27 08:51 UTC, jagnani73 commented
Hey @elliott-w !
Thank you for your PR! I didn't use CSS modules because I didn't want to write twelve separate classes with pretty much the same styles.
The incrementing id is a pretty neat trick, I had realised the bug was because of essentially the same styles being applied but couldn't figure a fix 😅

2022-01-27 08:58 UTC, elliott-w commented on src/index.tsx
> +  const [id, setId] = useState(0)
I added `number` if that's what you mean

2022-01-27 09:01 UTC, elliott-w commented
@jagnani73 Yeah now that you mention t it CSS modules don't make sense, I was just thinking some scoping would be nice haha. For what it's worth, aside from this bug, your marquee works really well, super happy with it! Couldn't find any other package that offered vertical sliding :)

2022-01-27 09:30 UTC, jagnani73 commented on src/index.tsx
> +  const [id, setId] = useState(0)
Thats what I meant, yes!

2022-01-27 09:31 UTC, jagnani73 commented
> 

Thank you!
Ill merge this as soon as the rebuild passes.

PS: Creating a donation :P

2022-01-27 09:32 UTC, jagnani73 commented
> @jagnani73 Yeah now that you mention t it CSS modules don't make sense, I was just thinking some scoping would be nice haha. For what it's worth, aside from this bug, your marquee works really well, super happy with it! Couldn't find any other package that offered vertical sliding :)
> 
> You should add a donation link!

Thank you!
Ill merge this as soon as the rebuild passes.

PS: Creating a donation :P

2022-01-27 09:33 UTC, jagnani73 approved these changes

2022-01-27 09:40 UTC, merged

2022-01-27 09:41 UTC, jagnani73 commented
Fixes #11

2022-07-11 06:45 UTC, jagnani73 commented
> @jagnani73 Yeah now that you mention t it CSS modules don't make sense, I was just thinking some scoping would be nice haha. For what it's worth, aside from this bug, your marquee works really well, super happy with it! Couldn't find any other package that offered vertical sliding :)
> 
> You should add a donation link!
> 

Hey @elliott-w !
I finally got a [donation link](https://github.com/sponsors/jagnani73) 😁